#!/bin/bash
MAX_VERSION="7.2.35"
PHP_VERSION=$(php -r 'echo PHP_VERSION;')

function version_compare() {
    COMPARE_OP=$1;
    TEST_VERSION=$2;
    RESULT=$(php -r 'echo version_compare(PHP_VERSION, "'"${TEST_VERSION}"'", "'"${COMPARE_OP}"'") ? "TRUE" : "";')

    test -n "${RESULT}";
}

echo "PHP VERSION: ${PHP_VERSION}"
if (version_compare ">" "${MAX_VERSION}"); then
  #PHP-PSR
  set -xe &&
    git clone https://github.com/jbboehr/php-psr.git /root/psr && \
    cd /root/psr && \
    phpize && \
    ./configure && \
    make && \
    make test && \
    make install && \
    echo "extension=psr.so" > /usr/local/etc/php/conf.d/29-psr.ini && \
    cd && rm -Rf /root/psr
fi


