#!/bin/bash
MAX_VERSION="7.2.34"
EXTRA_VERSION="7.3.9"
PHP_VERSION=$(php -r 'echo PHP_VERSION;')

function version_compare() {
    COMPARE_OP=$1;
    TEST_VERSION=$2;
    RESULT=$(php -r 'echo version_compare(PHP_VERSION, "'"${TEST_VERSION}"'", "'"${COMPARE_OP}"'") ? "TRUE" : "";')

    test -n "${RESULT}";
}

echo "PHP VERSION: ${PHP_VERSION}"
if (version_compare ">" "${MAX_VERSION}"); then
  if (version_compare ">" "${EXTRA_VERSION}"); then
    pecl install sqlsrv
  fi
  pecl install pdo_sqlsrv
else
  pecl install pdo_sqlsrv-5.6.1
fi
pecl clear-cache
docker-php-ext-enable pdo_sqlsrv
