#!/bin/bash
git update-index --chmod=+x ./build-php.sh
git update-index --chmod=+x ./test-cli.sh
git update-index --chmod=+x ./test-fpm.sh
git update-index --chmod=+x ./src/php/utils/install-composer
git update-index --chmod=+x ./src/php/utils/install-dumb-init
git update-index --chmod=+x ./src/php/utils/install-shush
git update-index --chmod=+x ./src/php/utils/install-gd
git update-index --chmod=+x ./src/php/utils/install-pdo-sqlsrv
git update-index --chmod=+x ./src/php/utils/install-phalcon
git update-index --chmod=+x ./src/php/utils/install-phalcon-devtools
git update-index --chmod=+x ./src/php/utils/docker/docker-php-dev-mode
git update-index --chmod=+x ./src/php/utils/docker/docker-php-entrypoint-init
git update-index --chmod=+x ./src/php/utils/docker/docker-php-ext-pdo-pgsql
git update-index --chmod=+x ./src/php/utils/docker/docker-php-ext-rdkafka
git update-index --chmod=+x ./src/php/utils/docker/docker-php-source-tarball
git update-index --chmod=+x ./src/php/utils/docker/php-fpm-healthcheck

sudo chmod +x ./build-php.sh
sudo chmod +x ./test-cli.sh
sudo chmod +x ./test-fpm.sh
sudo chmod +x ./src/php/utils/install-composer
sudo chmod +x ./src/php/utils/install-dumb-init
sudo chmod +x ./src/php/utils/install-shush
sudo chmod +x ./src/php/utils/install-gd
sudo chmod +x ./src/php/utils/install-pdo-sqlsrv
sudo chmod +x ./src/php/utils/install-phalcon
sudo chmod +x ./src/php/utils/install-phalcon-devtools
sudo chmod +x ./src/php/utils/docker/docker-php-dev-mode
sudo chmod +x ./src/php/utils/docker/docker-php-entrypoint-init
sudo chmod +x ./src/php/utils/docker/docker-php-ext-pdo-pgsql
sudo chmod +x ./src/php/utils/docker/docker-php-ext-rdkafka
sudo chmod +x ./src/php/utils/docker/docker-php-source-tarball
sudo chmod +x ./src/php/utils/docker/php-fpm-healthcheck