#!/bin/bash
set -xe

chown -R "${APP_OWNER}":"${APP_GROUP}"/var/www/html &
find /var/www/html -type d -exec chmod 0755 {} \; &
find /var/www/html -type f -exec chmod 644 {} \; &

chown -R "${APP_OWNER}":"${APP_GROUP}" /var/www/html
chmod -R g+rwX /var/www/html
